# ===========================================
# GUI自动化默认配置
# ===========================================

[automation]
# 图像查找超时时间（秒） - 用户可能需要根据设备性能调整
find_timeout = 15

# 默认图像识别置信度 - 用户可能需要根据显示效果调整
default_confidence = 0.8

# 等待时间基数（会根据device_level倍数调整）- 用户需要根据设备性能配置
sleep_short_base = 1
sleep_medium_base = 3  
sleep_long_base = 5