# ===========================================
# MCPSecTrace 系统默认配置 - 基础设置
# 注意：这是系统默认配置，升级时会被覆盖
# 如需自定义，请复制到 config/custom/ 目录下修改
# ===========================================

[system]
# 默认字符编码
encoding = "utf-8"
# 默认临时目录
temp_dir = "temp"
# 支持的操作系统
supported_os = ["Windows"]

[output_formats]
# 报告格式
report = "md"
# 数据导出格式  
data = "json"
# 截图格式
image = "png"

[mcp]
# MCP服务默认配置
default_log_level = "ERROR"
default_transport = "stdio"

# 服务名称映射
[mcp.service_names]
browser = "browser_tools"
huorong = "huorong"
hrkill = "hrkill" 
focus_pack = "focus_pack"
ioc = "ioc"