# ===========================================
# IOC威胁情报查询默认配置
# ===========================================

[ioc]
# 浏览器窗口尺寸 [宽度, 高度] - 用户可能根据屏幕大小调整
window_size = [1920, 1200]

# 等待时间配置（秒）- 用户可能根据网络速度和设备性能调整
scroll_wait_time = 2
element_timeout = 10
page_load_wait_seconds = 10
panel_expand_wait_time = 2