name: CI Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    name: 测试和代码质量检查
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: 安装uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
      
      - name: 设置Python环境
        run: uv python install 3.13
      
      - name: 安装依赖
        run: uv sync --extra dev
      
      - name: 代码格式检查
        run: |
          uv run black --check src/ tests/ || (echo "❌ 代码格式不正确，请运行: uv run black src/ tests/" && exit 1)
      
      - name: 导入排序检查  
        run: |
          uv run isort --check-only src/ tests/ || (echo "❌ 导入排序不正确，请运行: uv run isort src/ tests/" && exit 1)
      
      - name: 设置虚拟显示环境
        run: |
          # 安装虚拟显示环境支持GUI测试
          sudo apt-get update
          sudo apt-get install -y xvfb x11-utils xauth
          # 启动虚拟显示，设置为2048x1536分辨率以支持Chrome 1920x1200窗口
          export DISPLAY=:99
          Xvfb :99 -screen 0 2048x1536x24 &
          sleep 3
          # 创建X11认证文件
          touch ~/.Xauthority
          xauth add :99 . $(xxd -l 16 -p /dev/urandom)
          export XAUTHORITY=~/.Xauthority
          # 验证显示环境
          xwininfo -root -tree >/dev/null && echo "✅ 虚拟显示环境设置成功" || echo "❌ 虚拟显示环境设置失败"
      
      - name: 运行测试
        env:
          DISPLAY: ":99"
          XAUTHORITY: "/home/runner/.Xauthority"
          PYAUTOGUI_HEADLESS: "1"
        run: |
          # 运行完整的pytest测试套件，Windows专用功能在Linux环境下会被跳过
          uv run pytest -v || (echo "❌ 测试失败，请检查代码" && exit 1)